import {
    autoGeneratedHashKey,
    attribute,
    table
} from '@aws/dynamodb-data-mapper-annotations';
@table(process.env.TBL_PERSON)
export class Person{
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    nombre :String;

    @attribute()
    fechaNacimiento :String;

    @attribute()
    colorOjos :String;

    @attribute()
    genero :String;

    @attribute()
    colorCabello :String;

    @attribute()
    altura :String;

    @attribute()
    masa :String;

    @attribute()
    colorPiel :String;

    @attribute()
    mundoNacimiento :String;

    @attribute()
    peliculas :Array<String>;

    @attribute()
    especies :Array<String>;

    @attribute()
    naves :Array<String>;

    @attribute()
    vehiculos :Array<String>;

    @attribute()
    url :String;

    @attribute()
    fechaCreacion :String;

    @attribute()
    fechaModificacion :String;

    mappingToRequest=(obj:any)=>{
        this.id=obj.id;
        this.nombre =obj.nombre ;
        this.fechaNacimiento =obj.fechaNacimiento ;
        this.colorOjos =obj.colorOjos ;
        this.genero =obj.genero ;
        this.colorCabello =obj.colorCabello ;
        this.altura =obj.altura ;
        this.masa =obj.masa ;
        this.colorPiel =obj.colorPiel ;
        this.mundoNacimiento =obj.mundoNacimiento ;
        this.peliculas =obj.peliculas ;
        this.especies =obj.especies ;
        this.naves =obj.naves ;
        this.vehiculos =obj.vehiculos ;
        this.url =obj.url ;
    };
    mappingToIntegration=(obj:any)=>{
        this.id=obj.id;
        this.nombre =obj.name ;
        this.fechaNacimiento =obj.birth_year ;
        this.colorOjos =obj.eye_color ;
        this.genero =obj.gender ;
        this.colorCabello =obj.hair_color ;
        this.altura =obj.height ;
        this.masa =obj.mass ;
        this.colorPiel =obj.skin_color ;
        this.mundoNacimiento =obj.homeworld ;
        this.peliculas =obj.films ;
        this.especies =obj.species ;
        this.naves =obj.starships ;
        this.vehiculos =obj.vehicles ;
        this.url =obj.url ;
        this.fechaCreacion =obj.created ;
        this.fechaModificacion =obj.edited ;
    };
}